# AURA local Ollama transport fix â€” generated by AURA_CORRIGIR_URLOPEN_OLLAMA.ps1
# This module is auto-loaded by Python when this directory is on sys.path.
import os
import urllib.request
from urllib.parse import urlsplit

# Prevent WinHTTP/IE proxy DNS resolution for loopback Ollama requests.
os.environ['NO_PROXY'] = '127.0.0.1,localhost'
os.environ['no_proxy'] = '127.0.0.1,localhost'

_aura_direct_opener = urllib.request.build_opener(
    urllib.request.ProxyHandler({})
)
_aura_original_urlopen = urllib.request.urlopen

def _aura_urlopen(url, data=None, timeout=None, *, context=None):
    # Preserve normal urlopen behavior for non-Ollama URLs.
    raw = url.full_url if hasattr(url, 'full_url') else str(url)
    try:
        parsed = urlsplit(raw)
        is_local_ollama = parsed.hostname in ('127.0.0.1', 'localhost') and parsed.port == 11434
    except Exception:
        is_local_ollama = False
    if not is_local_ollama:
        if context is None:
            return _aura_original_urlopen(url, data=data, timeout=timeout)
        return _aura_original_urlopen(url, data=data, timeout=timeout, context=context)
    request = url if hasattr(url, 'full_url') else urllib.request.Request(raw, data=data)
    return _aura_direct_opener.open(request, timeout=timeout)

# Replace the function used by modules that imported urllib.request itself.
urllib.request.urlopen = _aura_urlopen
