import type { Agent, Topic } from "./types";

export const mockAgents: Agent[] = [
  {
    id: "a1",
    name: "coder",
    llm_provider: "openrouter",
    llm_model: "anthropic/claude-sonnet-4-6",
    max_tokens: 8192,
    system_prompt: "你是一个专业的编程助手，擅长 TypeScript、React 和 Go。代码简洁，注释少，直接解决问题。",
    scope: ["fs", "bash", "browser"],
    pinned: ["fs", "bash"],
    created_at: 1713500000,
    updated_at: 1713500000,
  },
  {
    id: "a2",
    name: "研究员",
    llm_provider: null,
    llm_model: "openai/gpt-4o",
    max_tokens: null,
    system_prompt: "你是一个深度研究助手，擅长分析和总结信息。善于从多个信息源交叉验证。",
    scope: null,
    pinned: null,
    created_at: 1713400000,
    updated_at: 1713400000,
  },
  {
    id: "a3",
    name: "翻译官",
    llm_provider: "openrouter",
    llm_model: "google/gemini-2.5-flash",
    max_tokens: 4096,
    system_prompt: null,
    scope: null,
    pinned: null,
    created_at: 1713300000,
    updated_at: 1713300000,
  },
];

export const mockTopics: Topic[] = [
  {
    id: "t1",
    name: "重构 agent-clip 架构",
    agent_id: "a1",
    agent_name: "coder",
    message_count: 24,
    created_at: 1713550000,
    last_message_at: 1713560000,
    has_active_run: false,
  },
  {
    id: "t2",
    name: "调研 WebRTC 方案",
    agent_id: "a2",
    agent_name: "研究员",
    message_count: 8,
    created_at: 1713450000,
    last_message_at: 1713455000,
  },
  {
    id: "t3",
    name: "闲聊",
    agent_id: null,
    agent_name: null,
    message_count: 5,
    created_at: 1713350000,
    last_message_at: 1713351000,
  },
  {
    id: "t4",
    name: "翻译产品文档",
    agent_id: "a3",
    agent_name: "翻译官",
    message_count: 12,
    created_at: 1713340000,
    last_message_at: 1713345000,
  },
];
