/* Kanteiro fullscreen chat — resposta fundamentada no snapshot atual.
 * A UI não decide risco; apenas consulta e narra o contrato retornado pelo Engine.
 */
'use strict';
(() => {
  const A = window.AURA_QUANTX_ADAPTER;
  if (!A) return;
  const $ = id => document.getElementById(id);
  const ctx = { state:null, charts:null, analysis:null, history:[], mode:'analysis' };
  const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const finite = value => Number.isFinite(Number(value))?Number(value):null;
  const first = (...values) => values.find(value => value !== null && value !== undefined && value !== '');
  const pct = value => { const n=finite(value);return n===null?'—':`${(n<=1?n*100:n).toFixed(1).replace('.',',')}%`; };
  const score = () => { const s=ctx.state?.score||{};return [s.home??s.h,s.away??s.a]; };
  const pair = key => { const v=ctx.state?.stats?.[key]??ctx.state?.[key];if(Array.isArray(v))return v;return [v?.home,v?.away]; };
  const fixture = () => ctx.state?.fixtureId || ctx.state?.fixture_id || null;
  const analysisRoot = () => ctx.analysis?.analysis || ctx.analysis?.result || ctx.analysis || {};
  const show = (id,value) => { const el=$(id);if(el)el.textContent=value; };
  const addMessage = (role, text, data) => { const box=$('messages');if(!box)return;const welcome=box.querySelector('.welcome-message');if(welcome)welcome.remove();const row=document.createElement('div');row.className=`message-row ${role}`;const bubble=document.createElement('div');bubble.className='message-bubble';bubble.innerHTML=`<div>${esc(text).replace(/\n/g,'<br>')}</div>`;if(data){const d=document.createElement('div');d.className='inline-data';d.innerHTML=data.map(x=>`<div><small>${esc(x[0])}</small><b>${esc(x[1])}</b></div>`).join('');bubble.appendChild(d)}const meta=document.createElement('div');meta.className='message-meta';meta.innerHTML=`<span>${new Date().toLocaleTimeString('pt-BR',{hour12:false})}</span><button data-speak="${esc(text)}">Ouvir</button><button data-copy="${esc(text)}">Copiar</button><button data-sources="1">Ver fontes</button>`;bubble.appendChild(meta);const av=document.createElement('span');av.className='mini-avatar';av.textContent=role==='user'?'EU':'K';row.appendChild(bubble);row.appendChild(av);box.appendChild(row);box.scrollTop=box.scrollHeight;}
  const ask = async prompt => { const clean=String(prompt||'').trim();if(!clean)return;addMessage('user',clean);ctx.history.push({role:'user',content:clean});$('typing').hidden=false;try{const data=await A.sendChat({message:clean,fixtureId:fixture(),context:buildContext(),systemContext:buildSystemContext(),history:ctx.history.slice(-12),speak:true});const reply=data?.reply||data?.message||data?.error||'O Engine não retornou resposta.';$('typing').hidden=true;addMessage('assistant',reply,buildDataCard(data?.analysis||ctx.analysis));ctx.history.push({role:'assistant',content:reply});try{if(A&&typeof A.speak==='function'&&reply){A.speak(String(reply).replace(/[*_`#]/g,'').replace(/\s+/g,' ').trim());}}catch(_){}if(data?.analysis){ctx.analysis=data.analysis;renderContext()}}catch(error){$('typing').hidden=true;addMessage('assistant',`Não consegui consultar o Engine: ${error?.message||error}`);}};
  const buildDataCard = analysis => { const r=analysis?.analysis||analysis||{};const risk=r.risk||{};const p=first(r.calibrated_probability,r.p_calibrated,r.corner_prob,r.probability);return [['Probabilidade ajustada',pct(p)],['Mercado',pct(first(r.market_prob,r.p_market))],['Vantagem',pct(first(r.edge,r.ev))],['Exposição',pct(first(risk.exposure,r.final_exposure,0))]]; };
  const buildContext = () => { const [hs,as]=score();const s=ctx.state||{};const stats=s.stats||{};return {fixtureId:fixture(),home:s.home,away:s.away,score:{home:hs,away:as},minute:s.minute,liveStatus:s.liveStatus,stats,events:(ctx.charts?.timeline?.events||s.matchEvents||[]).slice(-20),charts:{readiness:ctx.charts?.readiness||{},available:ctx.charts?.signals?.sources||[]},quality:s.quality||null,analysis:analysisRoot()}; };
  const buildSystemContext = () => ({view:'kanteiro-fullscreen',mode:ctx.mode,voiceAvailable:true,fixtureLock:true,failClosed:true});
  function renderContext(){const s=ctx.state||{};const [hs,as]=score();show('topMatch',s.home&&s.away?`${s.home} × ${s.away}`:'Aguardando captura');show('topScore',`${hs??'—'} × ${as??'—'}`);show('topMinute',s.minute!=null?`${s.minute}'`:'—');show('contextMinute',s.minute!=null?`${s.minute}'`:'—');show('homeTeam',s.home||'Casa');show('awayTeam',s.away||'Fora');show('homeScore',hs??'—');show('awayScore',as??'—');show('fixtureId',fixture()||'—');show('captureStatus',s.liveStatus==='live'?'OK':'—');const fresh=first(s.freshness?.score,s.quality?.freshness,s.capture?.freshness);show('topFresh',fresh==null?'N/D':pct(fresh));const a=analysisRoot();const risk=a.risk||{};const decision=String(first(a.decision,a.action,a.signal,'BLOCK')).toUpperCase();show('decisionState',/BLOCK|STOP|RED/.test(decision)?'BLOQUEADO':decision);show('decisionExposure',pct(first(risk.exposure,risk.final_exposure,0)));const issue=(a.data_integrity?.issues||[]).slice(0,2);$('reasonChips').innerHTML=(issue.length?issue:['POLÍTICA SEGURA ATIVA']).map(x=>`<span>${esc(String(x).replaceAll('_',' ').toUpperCase())}</span>`).join('');const corners=pair('corners');show('cornerNow',`${corners?.[0]??'—'} — ${corners?.[1]??'—'}`);const events=ctx.charts?.timeline?.events||[];const cornerEvents=events.filter(e=>/corner|escanteio|canto/i.test(String(e.type||e.label||'')));show('cornerLast',cornerEvents.at(-1)?.minute!=null?`${cornerEvents.at(-1).minute}'`:'N/D');show('corner5',cornerEvents.length?String(cornerEvents.filter(e=>s.minute!=null&&Number(s.minute)-Number(e.minute)<=5).length):'N/D');show('cornerP5',pct(first(a.corner_prob,a.probability,a.model_prob)));renderCharts();renderSources();}
  function renderCharts(){const box=$('chartLinks');if(!box)return;box.innerHTML='';const defs=[['Pressão','appm'],['xG','xg'],['Linha do tempo','timeline'],['Odds','oddsOscillation'],['Momento do xG','macdXg'],['Pressão relativa','pbar'],['Histórico','h2h'],['Radar','radar']];defs.forEach(([label,key])=>{const status=ctx.charts?.readiness?.[key]||ctx.charts?.[key]?.status||'pending';const b=document.createElement('button');b.innerHTML=`<span>${label}</span><i class="${status==='ready'?'':'warn'}"></i>`;b.onclick=()=>ask(`Mostre e explique o gráfico ${label}, informando a origem e se os dados estão prontos.`);box.appendChild(b)});}
  function renderSources(){const box=$('sourceGrid');if(!box)return;const sources=[['Rede',ctx.charts?.netSeries?.length?'OK':'N/D'],['Gráficos',ctx.charts?.seriesCount?'OK':'N/D'],['Eventos',ctx.charts?.timeline?.status==='ready'?'OK':'Aviso'],['Mercado',ctx.charts?.oddsOscillation?.status==='ready'?'OK':'Ausente']];box.innerHTML=sources.map(x=>`<div>${x[0]}<b class="${x[1]==='Ausente'?'bad':x[1]==='Aviso'?'warn':''}">${x[1]}</b></div>`).join('');}
  function renderQuickQuestions(){const questions=['Resumir os escanteios','Qual a acertividade agora?','Por que bloqueou?','Comparar modelo e mercado','A odd está contra o sinal?','Foco nos próximos 5 minutos','Comparar a pressão casa/fora','Analisar o mercado de gols','Ver fontes dos dados','O que mudou agora?','Falar o resumo','Checklist de veracidade'];const box=$('quickQuestions');box.innerHTML=questions.map(q=>`<button data-question="${esc(q)}">${esc(q)}</button>`).join('');box.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>ask(b.dataset.question));}
  async function refresh(){ctx.state=await A.getState();ctx.charts=await A.getCharts();ctx.analysis=await A.getAnalysis(fixture());renderContext();}
  function bind(){renderQuickQuestions();$('composer').onsubmit=e=>{e.preventDefault();const input=$('chatInput');const text=input.value.trim();input.value='';ask(text)};$('chatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('composer').requestSubmit()}};$('speakHeader').onclick=$('speakButton').onclick=async()=>{const text=`${$('decisionState').textContent}. ${$('cornerP5').textContent} nos próximos cinco minutos. ${$('reasonChips').textContent}`;const r=await A.speak(text);show('readingStatus',r.ok?'falando o resumo':'voz indisponível')};$('backCentral').onclick=()=>A.openCentral();$('openWindow').onclick=()=>window.open(location.href,'_blank','noopener');$('hideContext').onclick=()=>document.querySelector('.context-rail').classList.toggle('hidden');document.querySelectorAll('.context-action').forEach(b=>b.onclick=()=>ask(b.dataset.question));document.querySelectorAll('.chat-modes button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chat-modes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');ctx.mode=b.dataset.mode;ask(`Mude para o modo ${b.textContent.trim()} e explique a situação atual da partida.`)});$('contextButton').onclick=()=>ask('Anexe ao raciocínio o contexto completo da partida e liste as fontes disponíveis.');$('micButton').onclick=()=>show('readingStatus','microfone: use a captura de voz da extensão');$('messages').onclick=e=>{const speak=e.target.closest('[data-speak]');const copy=e.target.closest('[data-copy]');if(speak)A.speak(speak.dataset.speak);if(copy)navigator.clipboard?.writeText(copy.dataset.copy)};}
  async function boot(){bind();const prefill=sessionStorage.getItem('aura_kanteiro_prefill');if(prefill){sessionStorage.removeItem('aura_kanteiro_prefill');setTimeout(()=>ask(prefill),250)}await refresh();setInterval(refresh,4000)}
  boot();
})();
