# AURA — correção única do erro urlopen / Errno 11001 no Ollama
# Execute como Administrador no PowerShell.
# A correção é reversível: cria backup e instala sitecustomize.py somente em C:\aura\scripts.

$ErrorActionPreference = 'Stop'
$AURA = 'C:\aura\scripts'
$Site = Join-Path $AURA 'sitecustomize.py'
$Stamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$Backup = Join-Path $AURA ("backup_urlopen_" + $Stamp)

if (-not (Test-Path $AURA)) {
    throw "Pasta não encontrada: $AURA"
}

New-Item -ItemType Directory -Path $Backup -Force | Out-Null
if (Test-Path $Site) {
    Copy-Item $Site (Join-Path $Backup 'sitecustomize.py') -Force
}

@'
# AURA local Ollama transport fix — generated by AURA_CORRIGIR_URLOPEN_OLLAMA.ps1
# This module is auto-loaded by Python when this directory is on sys.path.
import os
import urllib.request
from urllib.parse import urlsplit

# Prevent WinHTTP/IE proxy DNS resolution for loopback Ollama requests.
os.environ['NO_PROXY'] = '127.0.0.1,localhost'
os.environ['no_proxy'] = '127.0.0.1,localhost'

_aura_direct_opener = urllib.request.build_opener(
    urllib.request.ProxyHandler({})
)
_aura_original_urlopen = urllib.request.urlopen

def _aura_urlopen(url, data=None, timeout=None, *, context=None):
    # Preserve normal urlopen behavior for non-Ollama URLs.
    raw = url.full_url if hasattr(url, 'full_url') else str(url)
    try:
        parsed = urlsplit(raw)
        is_local_ollama = parsed.hostname in ('127.0.0.1', 'localhost') and parsed.port == 11434
    except Exception:
        is_local_ollama = False
    if not is_local_ollama:
        if context is None:
            return _aura_original_urlopen(url, data=data, timeout=timeout)
        return _aura_original_urlopen(url, data=data, timeout=timeout, context=context)
    request = url if hasattr(url, 'full_url') else urllib.request.Request(raw, data=data)
    return _aura_direct_opener.open(request, timeout=timeout)

# Replace the function used by modules that imported urllib.request itself.
urllib.request.urlopen = _aura_urlopen
'@ | Set-Content -Path $Site -Encoding UTF8

Write-Host "Correção instalada em: $Site" -ForegroundColor Green
Write-Host "Backup criado em: $Backup" -ForegroundColor Yellow

# Confirma que o módulo Python compila e que o Ollama responde em loopback.
$Python = Get-Command python -ErrorAction SilentlyContinue
if (-not $Python) { throw 'Python não foi encontrado no PATH.' }
& $Python.Source -m py_compile $Site
if ($LASTEXITCODE -ne 0) { throw 'Falha de sintaxe em sitecustomize.py.' }

$Tcp = Test-NetConnection -ComputerName 127.0.0.1 -Port 11434 -InformationLevel Quiet
if (-not $Tcp) {
    Write-Host 'A correção foi instalada, mas o Ollama não está à escuta na porta 11434.' -ForegroundColor Red
    Write-Host 'Abra o Ollama ou execute "ollama serve" e rode o painel novamente.' -ForegroundColor Yellow
    exit 2
}

Set-Location $AURA
Write-Host 'TCP Ollama OK.' -ForegroundColor Green
Write-Host ''
Write-Host 'Agora inicie novamente o painel que apresentava [FALHA NA API].' -ForegroundColor Cyan
Write-Host 'Exemplo de teste do harness:' -ForegroundColor Yellow
Write-Host 'python .\AURA_HARNESS_CORE.py --reparar'
Write-Host ''
Write-Host 'Se o painel for um Python executado a partir de outra pasta, use:' -ForegroundColor Yellow
Write-Host "`$env:PYTHONPATH = '$AURA'; python 'CAMINHO_DO_SEU_PAINEL.py'"
